spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-poo-size: 5
    password: udemy
    url: jdbc:postgresql://localhost:5432/companies-test
    username: debuggeandoideas-test
